version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_CREATE_TOPICS=topic:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"

  auth-service:
    container_name: auth
    build: ./auth
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongodb:27017/kafka-node
      - KAFKA_TOPIC=topic
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
      - kafka
      - mongodb
