apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request
  template:
    metadata:
      labels:
        app: request
    spec:
      containers:
        - name: request
          image: credit-scoring/request
          env:
            - name: MONGO_URI
              value: "mongodb+srv://credit-scoring-admin:admin@cluster-backend.gp6s4fc.mongodb.net/credit-scoring"
            - name: JWT_KEY
              value: "rahasiabgtanjir"
---
apiVersion: v1
kind: Service
metadata:
  name: request-srv
spec:
  selector:
    app: request
  ports:
    - name: request
      protocol: TCP
      port: 3000
      targetPort: 3000
