name: deploy-auth

on:
  push:
    branches:
      - "dev"
    paths:
      - "auth/**"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker images

      - run: cd auth && docker build -t fathonizkr/auth .
      - run: docker push fathonizkr/auth

      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: credit-scoring-384712
          service_account_email: ${{ secrets.GCLOUD_AUTH_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}

      - run: gcloud --quiet auth configure-docker

      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: credit-scoring
          location: asia-southeast2
          credentials: ${{ secrets.GCLOUD_AUTH_KEY }}
          project_id: credit-scoring-384712

      - run: gcloud container clusters get-credentials credit-scoring --region asia-southeast2 --project credit-scoring-384712
      - run: kubectl rollout restart deployment auth-depl
