name: deploy-request

on:
  push:
    branches:
      - "dev"
    paths:
      - "request/**"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - "request/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker images
      - run: cd request && docker build -t fathonizkr/request .
      - run: docker push fathonizkr/request
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-becs
      - run: kubectl rollout restart deployment request-depl
